### PR TITLE
Add (composer) plex-utills

### PR DESCRIPTION
**Pull request by fscorrupt**

### CODE REVIEW

**Comment by doob187** [comment]
///
add wiki
add script to print token from plex ;-)
///


add intrsuctions 

then we can merg them 

without them NO !

**Review by doob187 — CHANGES_REQUESTED** [review]
see comment

**Comment by doob187** [comment]
script is added to print the token
token script is builded 

now the documentation plz

**Review by fscorrupt — COMMENTED** [review]
Added short How-To

**Comment by doob187** [comment]
Wiki is left  to do

**Review by doob187 — APPROVED** [review]

**Comment by doob187** [comment]
@drag0n141 plz review

**Review by drag0n141 — APPROVED** [review]

**Pull request merged**
