### PR TITLE
Create yacht.yml

### PR DESCRIPTION
**Pull request by mrfret**
Thought this was already in addons, but maybe not.

### CODE REVIEW

**Comment by drag0n141** [comment]
Check the Sample yml and fix the yml, there are many things wrong.

**Comment by mrfret** [comment]
fixed conflicts (hopefully)

**Review by drag0n141 — APPROVED** [review]

**Comment by drag0n141** [comment]
@mergify rebase

**Comment by drag0n141** [comment]
Added.

**Pull request closed without merging**
