### PR TITLE
#patch update authelia configuration.yml

### PR DESCRIPTION
**Pull request by doob187**
https://github.com/authelia/authelia/commit/158783a9d4d9bcd1c037601e25205ebff46daee8

See changes

### CODE REVIEW

**Comment by doob187** [comment]
#patch

**Comment by aelfa** [comment]
REVIEWED

**Review by drag0n141 — CHANGES_REQUESTED** [review]
i Think theme: under server and jwt_secret under log needs to be deleted. And Bantime needs to be 48h with only 48 it throws an error.

**Comment by doob187** [comment]
For theme here 

https://github.com/authelia/authelia/blob/158783a9d4d9bcd1c037601e25205ebff46daee8/config.template.yml#L13

**Comment by drag0n141** [comment]
Yes but its double :)

**Review by drag0n141 — APPROVED** [review]
Perfect :)

**Comment by doob187** [comment]
#patch

**Pull request merged**
