### PR TITLE
Update mount.yml

### PR DESCRIPTION
**Pull request by brtbach**
added ram cache for mount
note: edit path to /ram_cache in mount.env

### CODE REVIEW

**Comment by doob187** [comment]
Create overwrite environment 
Add value  to mount.env ( @doob187 )

**Review by doob187 — CHANGES_REQUESTED** [review]
Create overwrite environment

**Comment by brtbach** [comment]
is there another way to use ram cache beside mounting /dev/shm/ to container?

**Review by doob187 — CHANGES_REQUESTED** [review]
Need adjustment inside the docker first

**Comment by doob187** [comment]
This PR has not had any activity in 30 days. Marking it stale. It will be closed in 14 days.

**Pull request closed without merging**
