### PR TITLE
Created pihole-updatelists | Proposed changes to backup script

### PR DESCRIPTION
**Pull request by aelfa**
1. Created pihole-updatelists yml (A custom pihole image https://github.com/jacklul/pihole-updatelists)
2. Proposed changes to the backup script for more efficient and managed backups

### CODE REVIEW

**Comment by doob187** [comment]
Don't mix up them

**Comment by doob187** [comment]
https://github.com/dockserver/dockserver/blob/8e7d6d32c6f2f50dac94a19b09668d4e5d9982df/apps/.installer/ubuntu.sh#L98


https://github.com/dockserver/dockserver/blob/8e7d6d32c6f2f50dac94a19b09668d4e5d9982df/apps/.installer/ubuntu.sh#L133


https://github.com/dockserver/dockserver/blob/8e7d6d32c6f2f50dac94a19b09668d4e5d9982df/apps/.installer/ubuntu.sh#L168

https://github.com/dockserver/dockserver/blob/8e7d6d32c6f2f50dac94a19b09668d4e5d9982df/apps/.installer/ubuntu.sh#L210

https://github.com/dockserver/dockserver/blob/8e7d6d32c6f2f50dac94a19b09668d4e5d9982df/apps/.installer/ubuntu.sh#L260

**Comment by doob187** [comment]
All this  options needs a triple  check 
Not all user runs the new backups 

So older backups can't restore then

**Comment by aelfa** [comment]
@doob187 Just omit the hostname then the rest should be fine.
But the hostname is important for someone running multiple servers and backing up from the script.

**Comment by doob187** [comment]
Remove Hostname  and all is good

**Comment by doob187** [comment]
Each Server xan use a different  storage folder 
Uswr can choose them self 

Hostname  could  be create  weird issues when the User runs the basic install of Hetznet as sample

The Hostnqme is always the basic install name.
So it just one folder folder .. one deeper location.. so its not better.

More complex  = more failed / weird issues

**Comment by aelfa** [comment]
Yeah they can choose but not if they're running backups of the script directly. Right?

**Comment by doob187** [comment]
When the script runs you can always change the name.of the storage location.

The folder will always pulled before it's created the tar.gz

**Comment by doob187** [comment]
https://github.com/aelfa/dockserver/blob/a4dddae4b28e8c15a37cdc82e6f28a8755cf470d/scripts/backup/backupdate.sh#L48

This Linr

**Pull request closed without merging**
