### PR TITLE
Create pihole-updatelists.yml

### PR DESCRIPTION
**Pull request by aelfa**

### CODE REVIEW

**Comment by aelfa** [comment]
@doob187 Review whenever you get the time to.

**Comment by aelfa** [comment]
I think we should also include deleting backups older than a specific date. Like 7 days, 1 month etc.

**Comment by aelfa** [comment]
Or maybe overwriting the previous ones once a certain number is reached. Like rsnapshot does e.g. alpha beta gamma etc.

**Comment by drag0n141** [comment]
> I think we should also include deleting backups older than a specific date. Like 7 days, 1 month etc.

Yes that would be nice :)

**Review by drag0n141 — APPROVED** [review]
Looks good :)

**Comment by aelfa** [comment]
@DrAg0n141 Added :)

**Comment by aelfa** [comment]
```bash
## weekday name (e.g., Sunday) = 7 days retention ##
STORAGE=$(date '+%A')

## day of month (e.g., 01) = 30-31 days retention ##
#STORAGE=$(date '+%d')

## sample date 2021-07-22 = for the paranoids ##
#STORAGE=$(date "+%Y-%m-%d")
```

**Comment by doob187** [comment]
Made 2 separate once 
Don't mix up the PR

**Review by doob187 — COMMENTED** [review]
HOSTNAME option 

Can't work 

It's pulled the Storage folder the  Restore 
Need also changes in the backup and restore option unders apps

**Pull request closed without merging**
